[workspace]
members = [
    "modules/wormhole-cctp",
    "programs/circle-integration",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0-alpha.8"
authors = ["Wormhole Contributors"]
license = "Apache-2.0"
homepage = "https://wormhole.com"
repository = "https://github.com/wormhole-foundation/wormhole-circle-integration"

[workspace.dependencies.wormhole-cctp-solana]
path = "modules/wormhole-cctp"
default-features = false

[workspace.dependencies.wormhole-raw-vaas]
version = "0.2.0-alpha.2"

[workspace.dependencies.wormhole-solana-vaas]
version = "0.2.0-alpha.16"
features = ["anchor"]

[workspace.dependencies.anchor-lang]
version = "=0.30.0"
features = ["derive", "init-if-needed"]

[workspace.dependencies]
wormhole-io = "0.1.3"
anchor-spl = "=0.30.0"
solana-program = "1.17.20"
hex = "0.4.3"
ruint = "1.9.0"
cfg-if = "1.0"
hex-literal = "0.4.1"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1